# Copyright 2024-2026 Innovyou srl <http://www.innovyou.it>
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    "name": "ITA - Supporto IVA 74-ter - Fattura elettronica",
    "version": "18.0.1.0.0",
    "development_status": "Alpha",
    "category": "Localization/Italy",
    "summary": "Supporto IVA secondo art. 74-ter, DPR 633/72 - Agenzie viaggi "
    "e turismo - per la fattura elettronica (FatturaPA)",
    "author": "Innovyou, Odoo Community Association (OCA)",
    "maintainers": ["eLBati", "LorenzoC0"],
    "website": "https://github.com/OCA/l10n-italy",
    "license": "AGPL-3",
    # NOTE (v18 port): the Odoo 16 module depended on the OCA
    # `l10n_it_fatturapa_out` + `l10n_it_reverse_charge` stack, which does NOT
    # exist in Odoo 18. FatturaPA is now generated by CORE `l10n_it_edi`;
    # the third-party-issuer block ("Terzo intermediario / Soggetto emittente")
    # is provided by OCA `l10n_it_edi_sender_partner`, which we depend on and
    # which transitively pulls in `l10n_it_edi` + `l10n_it_edi_extension`.
    "depends": [
        "account",
        "l10n_it_edi_sender_partner",
    ],
    "data": [
        "views/res_partner_views.xml",
        "views/account_move_views.xml",
        "views/res_config_settings_views.xml",
        "data/invoice_it_template.xml",
    ],
    "installable": True,
}
